version: "3"
services:
        login-app:
            container_name: login-app
            image: latest123/login-app
            restart: always
            build: .
            ports:
              - "7500:7500"
            links:
              - mongo
            environment:
              WAIT_HOSTS: mongo:27017
        mongo:
              container_name: mongo
              image: mongo
              volumes:
                - C:/mongodb/dba:/data/db
              ports:
                - '27017:27017'
              restart: unless-stopped
